# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\editCardsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditCardsWindow(object):
    def setupUi(self, EditCardsWindow):
        EditCardsWindow.setObjectName("EditCardsWindow")
        EditCardsWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(EditCardsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 10, 701, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.definitionLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.definitionLine.setObjectName("definitionLine")
        self.gridLayout.addWidget(self.definitionLine, 1, 0, 1, 1)
        self.definitionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.definitionLabel.setObjectName("definitionLabel")
        self.gridLayout.addWidget(self.definitionLabel, 0, 0, 1, 1)
        self.valueLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.valueLine.setObjectName("valueLine")
        self.gridLayout.addWidget(self.valueLine, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 3, 1, 1, 1)
        self.valueLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valueLabel.setObjectName("valueLabel")
        self.gridLayout.addWidget(self.valueLabel, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.cardsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.cardsTable.setGeometry(QtCore.QRect(50, 160, 700, 250))
        self.cardsTable.setMaximumSize(QtCore.QSize(700, 250))
        self.cardsTable.setObjectName("cardsTable")
        self.cardsTable.setColumnCount(0)
        self.cardsTable.setRowCount(0)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 460, 701, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deleteButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_2.addWidget(self.deleteButton, 1, 1, 1, 1)
        self.delDefLine = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.delDefLine.setObjectName("delDefLine")
        self.gridLayout_2.addWidget(self.delDefLine, 1, 0, 1, 1)
        self.defLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.defLabel.setObjectName("defLabel")
        self.gridLayout_2.addWidget(self.defLabel, 0, 0, 1, 1)
        EditCardsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EditCardsWindow)
        self.statusbar.setObjectName("statusbar")
        EditCardsWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(EditCardsWindow)
        self.toolBar.setObjectName("toolBar")
        EditCardsWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSettings = QtWidgets.QAction(EditCardsWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName("actionSettings")
        self.actionStatistics = QtWidgets.QAction(EditCardsWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatistics.setIcon(icon1)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionExit = QtWidgets.QAction(EditCardsWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionStatistics)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(EditCardsWindow)
        self.actionExit.triggered.connect(EditCardsWindow.close)
        QtCore.QMetaObject.connectSlotsByName(EditCardsWindow)

    def retranslateUi(self, EditCardsWindow):
        _translate = QtCore.QCoreApplication.translate
        EditCardsWindow.setWindowTitle(_translate("EditCardsWindow", "Редактирование карточек"))
        self.definitionLabel.setText(_translate("EditCardsWindow", "Определение"))
        self.addButton.setText(_translate("EditCardsWindow", "Добавить"))
        self.valueLabel.setText(_translate("EditCardsWindow", "Значение"))
        self.deleteButton.setText(_translate("EditCardsWindow", "Удалить"))
        self.delDefLine.setPlaceholderText(_translate("EditCardsWindow", "Введите название определения"))
        self.defLabel.setText(_translate("EditCardsWindow", "Определение:"))
        self.toolBar.setWindowTitle(_translate("EditCardsWindow", "toolBar"))
        self.actionSettings.setText(_translate("EditCardsWindow", "Settings"))
        self.actionSettings.setToolTip(_translate("EditCardsWindow", "Settings open"))
        self.actionStatistics.setText(_translate("EditCardsWindow", "Statistics"))
        self.actionStatistics.setToolTip(_translate("EditCardsWindow", "Statistics open"))
        self.actionExit.setText(_translate("EditCardsWindow", "Exit"))
        self.actionExit.setToolTip(_translate("EditCardsWindow", "Exit window"))
